language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjansson-dev
  - sudo apt-get install -y liblua5.2-dev
  - sudo apt-get install -y libx264-dev
  - sudo apt-get install -y protobuf-compiler
script: ./build.sh

env:
  global:
    - CODECOV_TOKEN="86c0cf19-699e-49f9-b6d4-4d5c214e70d5"

after_success:
  - bash <(curl -s https://codecov.io/bash)
